name: Build and Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Enable corepack
        run: corepack enable yarn
      - name: Install deps
        run: yarn global add wasm-pack && yarn install
      - name: Build
        run: yarn wasm && yarn build
      - name: Setup SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - name: Deploy
        run: tar Czcvf $(dirname dist/.) - $(basename dist/.) | ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "cat > ${{ secrets.SERVER_DESTINATION }}/${{ github.sha }}.tgz"
