name: Build and Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - name: Set node version to 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install deps
        run: pnpm add --global wasm-pack && pnpm install
      - name: Build
        run: pnpm wasm && pnpm build
      - name: Setup SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - name: Deploy
        run: tar Czcvf $(dirname dist/.) - $(basename dist/.) | ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cat > ${{ secrets.WORK_DIR }}/build/${{ github.sha }}.tgz && tar xzvf ${{ secrets.WORK_DIR }}/build/${{ github.sha }}.tgz -C ${{ secrets.WORK_DIR }}/html"
      - name: Cleanup
        run: rm -rf ~/.ssh
